### PR TITLE
build 1.6.1 release

### PR DESCRIPTION
**Pull request by ocefpaf**
@isuruf I'd love to test delvewheel now that we have it in conda-forge. If you have some free time can you help me out implementing it here?

### CODE REVIEW

**Comment by ocefpaf** [comment]
```
C:\Users\filipe\Downloads>pip install netCDF4-1.6.1-cp310-cp310-win_amd64.whl
Processing c:\users\filipe\downloads\netcdf4-1.6.1-cp310-cp310-win_amd64.whl
Collecting numpy>=1.9
  Downloading numpy-1.23.3-cp310-cp310-win_amd64.whl (14.6 MB)
     ---------------------------------------- 14.6/14.6 MB 5.9 MB/s eta 0:00:00
Collecting cftime
  Using cached cftime-1.6.1-cp310-none-win_amd64.whl (156 kB)
Installing collected packages: numpy, cftime, netCDF4
  WARNING: The script f2py.exe is installed in 'C:\Users\filipe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts nc3tonc4.exe, nc4tonc3.exe and ncinfo.exe are installed in 'C:\Users\filipe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cftime-1.6.1 netCDF4-1.6.1 numpy-1.23.3

C:\Users\filipe\Downloads>cd netcdf4-python-master\test
C:\Users\filipe\Downloads\netcdf4-python-master\test>python run_all.py
not running tst_compression_quant.py ...
not running tst_compression_zstd.py ...
not running tst_compression_bzip2.py ...
not running tst_compression_blosc.py ...
not running tst_compression_szip.py ...

netcdf4-python version: 1.6.1
HDF5 lib version:       1.12.1
netcdf lib version:     4.8.1
numpy version           1.23.3
cython version          0.29.32
.s.EE.EE...........................................................................................
======================================================================
ERROR: runTest (tst_atts.VariablesTestCase)
testing attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\filipe\Downloads\netcdf4-python-master\test\tst_atts.py", line 183, in runTest
    ncdump_output = f.tocdl()
  File "src\netCDF4\_netCDF4.pyx", line 3490, in netCDF4._netCDF4.Dataset.tocdl
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

======================================================================
ERROR: runTest (tst_atts.VariablesTestCase)
testing attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\filipe\Downloads\netcdf4-python-master\test\tst_atts.py", line 137, in tearDown
    os.remove(self.file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'tst_atts.nc'

======================================================================
ERROR: test_fromcdl (tst_cdl.Test_CDL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\filipe\Downloads\netcdf4-python-master\test\tst_cdl.py", line 41, in setUp
    f.tocdl(outfile='ubyte.cdl',data=True)
  File "src\netCDF4\_netCDF4.pyx", line 3490, in netCDF4._netCDF4.Dataset.tocdl
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

======================================================================
ERROR: test_tocdl (tst_cdl.Test_CDL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\filipe\Downloads\netcdf4-python-master\test\tst_cdl.py", line 41, in setUp
    f.tocdl(outfile='ubyte.cdl',data=True)
  File "src\netCDF4\_netCDF4.pyx", line 3490, in netCDF4._netCDF4.Dataset.tocdl
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

----------------------------------------------------------------------
Ran 98 tests in 53.229s

FAILED (errors=4, skipped=1)
```

@jswhit only 4 tests are failing and they look like Windows file system peculiarities. I'll investigate them later but the wheel is fully working. I tested it with the default Python from the Microsoft store this time.

**Comment by jswhit** [comment]
@ocefpaf  Could you have your workflow upload the wheels to a github release? I can then manually download and re-upload to pypi using twine.

**Comment by ocefpaf** [comment]
> @ocefpaf Could you have your workflow upload the wheels to a github release?

Sure. I'll look into automating that.

> I can then manually download and re-upload to pypi using twine.

At the moment all the artifacts are here: https://github.com/ocefpaf/netcdf4-win-wheels/actions/runs/3047536213

One would need to download, unzip, and twine upload them. I'll make a manual release with those binaries for now. I just finished testing all the Python versions with a Python installation from [python.org](https://www.python.org/).

**Comment by ocefpaf** [comment]
Done: https://github.com/ocefpaf/netcdf4-win-wheels/releases/tag/v1.6.1

**Comment by jswhit** [comment]
great, thanks.  Looks like I can make a release now.

**Comment by isuruf** [comment]
> @ocefpaf Could you have your workflow upload the wheels to a github release?

> Sure. I'll look into automating that.

It already is automated.

**Comment by ocefpaf** [comment]
> It already is automated.

So I don't need to add the binaries when creating a tag? Nice. I'll try that next time. I did ended up using the drag-n-drop functionality for 1.6.1.

**Pull request merged**
